apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: cogrpc
  labels:
    project: {{ .Values.gcpProjectId | quote }}
    {{- include "gateway-crds.labels" . | nindent 4 }}
spec:
  healthCheck:
    type: HTTP
    port: 8082
