nameOverride: nats
nats:
  terminationGracePeriodSeconds: 30
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 100Mi
cluster:
  enabled: true
natsbox:
  enabled: false

securityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true
topologyKeys:
  - "kubernetes.io/hostname"
  - "topology.kubernetes.io/zone"
  - "topology.kubernetes.io/region"
