apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    "app.kubernetes.io/managed-by": Helm
    "meta.helm.sh/release-name": "${HELM_RELEASE_NAME}"
data:
  bucket: relaycorp-gateway-test-vault
  partial-vault.hcl: |2
    seal "gcpckms" {
      project    = "${CLOUDSDK_CORE_PROJECT}"
      region     = "global"
      key_ring   = "${VAULT_KMS_KEY_RING}"
      crypto_key = "${VAULT_KMS_AUTOUNSEAL_KEY}"
    }

    storage "gcs" {
      bucket     = "${VAULT_GCS_BUCKET}"
      ha_enabled = "true"
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-cd
  labels:
    "app.kubernetes.io/managed-by": Helm
    "meta.helm.sh/release-name": "${HELM_RELEASE_NAME}"
type: Opaque
data:
  service_account_key.json: "${VAULT_SA_KEY_BASE64}"
