repositories:
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

helmDefaults:
  wait: true

releases:
  - name: stan
    chart: nats/stan
    version: 0.7.2
    values:
      - defaults/stan.yml
    set:
      - name: store.sql.dbHost
        value: {{ requiredEnv "STAN_DB_HOST" | quote }}
      - name: store.sql.dbName
        value: {{ requiredEnv "STAN_DB_NAME" | quote }}
      - name: store.sql.dbUser
        value: {{ requiredEnv "STAN_DB_USER" | quote }}
      - name: store.sql.dbPassword
        value: {{ readFile "../secrets/stan-db-password" | quote }}
      - name: store.sql.source
        value: host={{ requiredEnv "STAN_DB_HOST" }} dbname={{ requiredEnv "STAN_DB_NAME" }} user={{ requiredEnv "STAN_DB_USER" }} password={{ readFile "../secrets/stan-db-password" }} sslmode=require
  - name: nats
    chart: nats/nats
    version: 0.7.2
    values:
      - defaults/nats.yml
  - name: vault
    chart: hashicorp/vault
    version: 0.8.0
    values:
      - defaults/vault.yml
    set:
      - name: server.extraEnvironmentVars.GOOGLE_PROJECT
        value: {{ requiredEnv "CLOUDSDK_CORE_PROJECT" | quote }}
    hooks:
      - events: [presync]
        showlogs: true
        command: vault/pre-install.sh
        args:
          - "{{`{{.Release.Name}}`}}"
