repositories:
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts
  - name: minio
    url: https://helm.min.io
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: relaycorp
    url: https://h.cfcr.io/relaycorp/public

helmDefaults:
  wait: true

releases:
  - name: stan
    chart: nats/stan
    version: 0.7.4
    values:
      - stan/values.yml.gotmpl
    labels:
      tier: backingService
  - name: nats
    chart: nats/nats
    version: 0.7.2
    values:
      - nats/values.yml
    labels:
      tier: backingService

  - name: minio
    chart: minio/minio
    version: 8.0.3
    values:
      - minio/values.yml.gotmpl
    labels:
      tier: backingService

  - name: vault
    chart: hashicorp/vault
    version: 0.8.0
    values:
      - vault/values.yml.gotmpl
    hooks:
      - events: [presync]
        showlogs: true
        command: vault/pre-install.sh
        args:
          - "{{`{{.Release.Name}}`}}"
          - "default"
      - events: [postsync]
        showlogs: true
        command: vault/post-install.sh
        args:
          - {{ requiredEnv "VAULT_KEYBASE_USERNAME" | quote }}
          - {{ requiredEnv "VAULT_KV_PREFIX" | quote }}
          - {{ requiredEnv "VAULT_GCS_BUCKET" | quote }}
          - "{{`{{.Release.Name}}`}}"
          - {{ requiredEnv "VAULT_ROOT_TOKEN_SECRET_ID" | quote }}
    labels:
      tier: backingService

  - name: gateway-crds
    chart: ./gateway-crds
    values:
      - gateway-crds/values.yml.gotmpl

  - name: gateway
    chart: relaycorp/relaynet-internet-gateway
    version: 1.16.0
    values:
      - gateway/values.yml.gotmpl
