repositories:
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts
  - name: minio
    url: https://helm.min.io
  - name: relaycorp
    url: https://h.cfcr.io/relaycorp/public

helmDefaults:
  wait: true

releases:
  - name: stan
    chart: nats/stan
    version: 0.7.2
    values:
      - stan/values.yml.gotmpl
  - name: nats
    chart: nats/nats
    version: 0.7.2
    values:
      - nats/values.yml

  - name: minio
    chart: minio/minio
    version: 8.0.3
    values:
      - minio/values.yml.gotmpl

  - name: gateway
    chart: relaycorp/relaynet-internet-gateway
    version: 1.16.0
    values:
      - gateway/values.yml.gotmpl
    strategicMergePatches:
      - apiVersion: networking.gke.io/v1beta2
        kind: ManagedCertificate
        metadata:
          name: {{ requiredEnv "GW_MANAGED_CERT_NAME" | quote }}
        spec:
          domains:
            - {{ requiredEnv "GW_POWEB_DOMAIN" | quote }}
            - {{ requiredEnv "GW_POHTTP_DOMAIN" | quote }}
            - {{ requiredEnv "GW_COGRPC_DOMAIN" | quote }}
