repositories:
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts

helmDefaults:
  wait: true

releases:
  - name: stan
    chart: nats/stan
    version: 0.7.2
    values:
      - defaults/stan.yml
    set:
      - name: store.sql.dbHost
        value: {{ requiredEnv "STAN_DB_HOST" | quote }}
      - name: store.sql.dbName
        value: {{ requiredEnv "STAN_DB_NAME" | quote }}
      - name: store.sql.dbUser
        value: {{ requiredEnv "STAN_DB_USER" | quote }}
      - name: store.sql.dbPassword
        value: {{ readFile "stan-db.secret" | quote }}
      - name: store.sql.source
        value: host={{ requiredEnv "STAN_DB_HOST" }} dbname={{ requiredEnv "STAN_DB_NAME" }} user={{ requiredEnv "STAN_DB_USER" }} password={{ readFile "stan-db.secret" }} sslmode=require
