# Vault's chart is too complicated to deploy so it has to be done separately. For example,
# `helmfile apply` would fail the first time round because the `helm diff` won't be able to
# read the Vault token.
#
# See also: https://github.com/hashicorp/vault-helm/issues/422

repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

helmDefaults:
  wait: true

releases:
  - name: vault
    chart: hashicorp/vault
    version: 0.8.0
    values:
      - vault/values.yml.gotmpl
    hooks:
      - events: [presync]
        showlogs: true
        command: vault/pre-install.sh
        args:
          - "{{`{{.Release.Name}}`}}"
          - "default"
      - events: [postsync]
        showlogs: true
        command: vault/post-install.sh
        args:
          - {{ requiredEnv "VAULT_KEYBASE_USERNAME" | quote }}
          - {{ requiredEnv "VAULT_KV_PREFIX" | quote }}
          - {{ requiredEnv "VAULT_GCS_BUCKET" | quote }}
          - "{{`{{.Release.Name}}`}}"
          - {{ requiredEnv "VAULT_ROOT_TOKEN_SECRET_ID" | quote }}
