repositories:
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts

helmDefaults:
  wait: true

releases:
  - name: stan
    chart: nats/stan
    version: 0.7.2
    values:
      - cloud-gateway/charts/defaults/stan.yml
    set:
      - name: store.sql.dbHost
        value: {{ requireEnv "DB_HOST" | quote }}
      - name: store.sql.dbName
        value: {{ requireEnv "DB_NAME" | quote }}
      - name: store.sql.dbUser
        value: {{ requireEnv "DB_USER" | quote }}
      - name: store.sql.dbPassword
        value: {{ readfile "/tmp/stan-db-secret" | quote }}
      - name: store.sql.source
        value: host={{ requireEnv "DB_HOST" }} dbname={{ requireEnv "DB_NAME" }} user={{ requireEnv "DB_USER" }} password={{ readfile "/tmp/stan-db-secret" }} sslmode=require
