repositories:
  - name: nats
    url: https://nats-io.github.io/k8s/helm/charts
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: minio
    url: https://helm.min.io
  - name: relaycorp
    url: https://h.cfcr.io/relaycorp/public

helmDefaults:
  wait: true

releases:
  - name: stan
    chart: nats/stan
    version: 0.7.2
    values:
      - stan/values.yml
    set:
      - name: store.sql.dbHost
        value: {{ requiredEnv "STAN_DB_HOST" | quote }}
      - name: store.sql.dbName
        value: {{ requiredEnv "STAN_DB_NAME" | quote }}
      - name: store.sql.dbUser
        value: {{ requiredEnv "STAN_DB_USER" | quote }}
      - name: store.sql.dbPassword
        value: {{ readFile "../secrets/stan-db-password" | quote }}
      - name: store.sql.source
        value: host={{ requiredEnv "STAN_DB_HOST" }} dbname={{ requiredEnv "STAN_DB_NAME" }} user={{ requiredEnv "STAN_DB_USER" }} password={{ readFile "../secrets/stan-db-password" }} sslmode=require
  - name: nats
    chart: nats/nats
    version: 0.7.2
    values:
      - nats/values.yml

  - name: minio
    chart: minio/minio
    version: 8.0.3
    values:
      - minio/values.yml
    set:
      - name: secretKey
        value: {{ readFile "../secrets/minio-secret-key" | quote }}

  - name: vault
    chart: hashicorp/vault
    version: 0.8.0
    values:
      - vault/values.yml
    set:
      - name: server.extraEnvironmentVars.GOOGLE_PROJECT
        value: {{ requiredEnv "CLOUDSDK_CORE_PROJECT" | quote }}
    hooks:
      - events: [presync]
        showlogs: true
        command: vault/pre-install.sh
        args:
          - "{{`{{.Release.Name}}`}}"
          - "default"
      - events: [postsync]
        showlogs: true
        command: vault/post-install.sh
        args:
          - {{ requiredEnv "VAULT_KEYBASE_USERNAME" | quote }}
          - {{ requiredEnv "VAULT_KV_PREFIX" | quote }}
          - {{ requiredEnv "VAULT_GCS_BUCKET" | quote }}
          - "{{`{{.Release.Name}}`}}"
          - {{ requiredEnv "VAULT_ROOT_TOKEN_SECRET_ID" | quote }}
