version: "1.0"
stages:
  - clone
  - deploy
  - configure
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    git: "github"
    stage: "clone"

  deploy:
    title: "Deploy Vault with Helm"
    type: helm
    stage: deploy
    arguments:
      action: install
      chart_name: vault
      chart_repo_url: https://helm.releases.hashicorp.com
      release_name: main
      helm_version: 3.1.3
      kube_context: ${{KUBERNETES_CONTEXT}}
      custom_value_files:
        - cloud-gateway/charts/defaults/vault.yml
      custom_values:
        - server_extraEnvironmentVars_GOOGLE__PROJECT=${{GCP_PROJECT_ID}}

  configure:
    title: Configure Vault
    type: freestyle
    stage: deploy
    image: codefresh/kubectl:1.18.2
    commands:
      - cloud-gateway/cf-pipelines/scripts/configure-vault.sh "${{KEYBASE_USERNAME}}" "${{VAULT_KV_PREFIX}}"
      - cf_export VAULT_INIT_PRESENT="$(find . -name vault-init.asc -maxdepth 1 -exec echo true \;)"

  upload_vault_keys:
    title: Upload Vault keys
    type: freestyle
    stage: configure
    image: google/cloud-sdk:318.0.0-alpine
    commands:
      - gcloud components install gsutil
    when:
      condition:
        all:
          vaultInitIsPresent: ${{VAULT_INIT_PRESENT}} == "true"
