version: "1.0"
stages:
  - clone
  - deploy
  - configure
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    git: "github"
    stage: "clone"

  deploy:
    title: "Deploy Vault with Helm"
    type: helm
    stage: deploy
    arguments:
      action: install
      chart_name: vault
      chart_repo_url: https://helm.releases.hashicorp.com
      release_name: main
      helm_version: 3.1.3
      kube_context: ${{KUBERNETES_CONTEXT}}
      custom_value_files:
        - cloud-gateway/charts/defaults/vault.yml
      custom_values:
        - server_extraEnvironmentVars_GOOGLE__PROJECT=${{GCP_PROJECT_ID}}

  configure:
    title: Configure Vault
    type: freestyle
    stage: configure
    image: codefresh/kubectl:1.18.2
    commands:
      - export POD_NAME="$(kubectl get pod -l app.kubernetes.io/name=vault --no-headers --output=jsonpath='{.items[0].metadata.name}')"
      - kubectl exec "${POD_NAME}" -- vault operator init -status
      - kubectl exec "${POD_NAME}" -- vault secrets enable -path=gw-keys kv-v2
