version: "1.0"
stages:
  - clone
  - deploy

steps:
  main_clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    git: "github"
    stage: "clone"

  temp:
    title: "Temp step"
    type: freestyle
    arguments:
      image: 'alpine:3.8'
      commands:
        - pwd
        - ls -lA

  deploy:
    title: "Deploy Vault with Helm"
    type: helm
    stage: deploy
    arguments:
      action: install
      chart_name: vault
      chart_repo_url: https://helm.releases.hashicorp.com
      release_name: main
      helm_version: 3.1.3
      kube_context: ${{KUBERNETES_CONTEXT}}
      custom_value_files:
        - cf-pipelines/defaults/vault.yml
