version: "1.0"
stages:
  - deprovision

steps:
  deploy:
    title: "Deprovision Vault with Helm"
    type: helm
    stage: deprovision
    arguments:
      action: auth
      helm_version: 3.1.3
      kube_context: ${{KUBERNETES_CONTEXT}}
      commands:
        - helm uninstall main
