version: "1.0"
stages:
  - "deploy"

steps:
  deploy:
    title: "Deploy with Helm"
    type: helm
    arguments:
      action: install
      chart_name: vault
      chart_repo_url: https://helm.releases.hashicorp.com
      release_name: main
      helm_version: 3.1.3
      kube_context: ${{KUBERNETES_CONTEXT}}
      custom_values:
        - 'server.dev.enabled=true'
        - 'server.image.extraEnvironmentVars.VAULT_DEV_ROOT_TOKEN_ID=letmein'
