name: "Continuous Integration"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci-main:
    uses: relaycorp/shared-workflows/.github/workflows/tfmodule-ci.yml@main
    with:
      path: tf-workspace
      terraform_version: 1.1.2

  ci-belgium:
    uses: relaycorp/shared-workflows/.github/workflows/tfmodule-ci.yml@main
    with:
      path: environments/belgium
      terraform_version: 1.6.6
